apiVersion: v1
kind: Pod
metadata:
  name: projectpod
spec:
  volumes:
  - name: localmount
    hostPath:
      path: /home/chad/newmount
  containers:
  - name: webserver
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
    volumeMounts:
      - mountPath: /home/chad/newmount
        name: localmount
  - name: dist
    image: debian
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    command: ["sh", "-c", "tail -f /dev/null"]

