apiVersion: v1
kind: Pod
metadata:
  name: projectpod
spec:
  containers:
  - name: webserver
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
    volumeMounts:
      - mountPath: /var/log/
        name: localmount
  - name: dist
    image: debian
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    command: ["sh", "-c", "tail -f /dev/null"]
  volumes:
    - name: localmount
      hostPath:
        path: /var/log/