apiVersion: apps/v1
kind: Deployment
metadata:
  name: projecttoday
spec:

  selector:
    matchLabels:
      app: projecttoday

  template:
    metadata:
      labels:
        app: projecttoday

    spec:

      volumes:
      - name: shared
        emptyDir: {}

      containers:
      - name: webserver
        image: nginx
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
        volumeMounts:
          - mountPath: /data
            name: shared

      - name: dist
        image: debian
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        command: ["sh", "-c", "tail -f /dev/null"]
        volumeMounts:
          - mountPath: /data
            name: shared
            
